image: python:3.7.3

pipelines:
  custom:
    check_version:
      - step:
          caches:
            - pip
          script:
            - git submodule update --init
            - python pipeline.py