image: python:3.7.3
options:
  max-time: 1
pipelines:
  custom:
    pull-requests:
      - step:
          script:
            - git submodule update --init
            - python twincat_version_manager.py